#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := test_framerate

EXTRA_COMPONENT_DIRS := ../../
EXTRA_COMPONENT_DIRS += ../camera_example_common/

include $(IDF_PATH)/make/project.mk

